### ISSUE TITLE
deprecated linter

### ISSUE THREAD

**Issue by nkt114** [OtusGolang/home_work#40]
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive.

Линтер досихпор прописан в .golangci.yml

**Comment by Antonboom** [comment]
@qwroot, в соответствии с README:

```
Используемая версия golangci-lint: v1.40.0
```

**Comment by qwroot** [comment]
Я использую версию 1.40.1. 

golangci-lint has version 1.40.1 built from 625445b on 2021-05-14T16:07:57Z

**Comment by Antonboom** [comment]
Закроется с https://github.com/OtusGolang/home_work/pull/42
